"""Render docs/MODEL_CARD.md from a run's metrics.json, so the card never drifts from the run."""

from __future__ import annotations

from collections.abc import Iterable, Sequence
from typing import Any

from credit_ranking.explain import REASONS
from credit_ranking.features import FEATURE_DESCRIPTIONS
from credit_ranking.schema import PROTECTED_ATTRIBUTES

UCI_CITATION = (
    'Source: UCI Machine Learning Repository, "Default of Credit Card Clients" '
    "(Yeh & Lien, 2009), CC BY 4.0. Taiwanese card holders, April-September 2005."
)
SYNTHETIC_NOTE = (
    "These figures come from the bundled **synthetic** sample and say nothing about "
    "real-world performance."
)


def table(headers: Sequence[str], rows: Iterable[Sequence[object]]) -> str:
    lines = ["| " + " | ".join(headers) + " |", "|" + "|".join("---" for _ in headers) + "|"]
    lines += ["| " + " | ".join(str(c) for c in row) + " |" for row in rows]
    return "\n".join(lines)


def pct(x: float | None) -> str:
    return "n/a" if x is None else f"{100 * x:.1f}%"


def num(x: float | None, digits: int = 3) -> str:
    return "n/a" if x is None else f"{x:.{digits}f}"


class _Card:
    def __init__(self, m: dict[str, Any], img_dir: str | None) -> None:
        self.m = m
        self.cfg: dict[str, Any] = m["config"]
        self.names: list[str] = list(m["models"])
        self.champ: dict[str, Any] = m["models"][m["champion_label"]]
        self.img_dir = img_dir

    def img(self, name: str, alt: str) -> str:
        return f"![{alt}]({self.img_dir}/{name})" if self.img_dir else ""

    def header(self) -> str:
        label = self.m["data"]["label"]
        note = SYNTHETIC_NOTE if "synthetic" in label.lower() else UCI_CITATION
        return (
            "# Model card: explainable credit work-queue ranker\n\n"
            f"Generated by `credit-rank model-card` from the training run on **{label}**. "
            f"Every number below is computed by the code in this repository on that data. {note}"
        )

    def details(self) -> str:
        cfg = self.cfg
        challengers = ", ".join(n for n in self.names if n != self.m["champion_label"])
        monotone = "on" if cfg["models"]["lightgbm"].get("monotone") else "off"
        constraints = ", ".join(
            f"`{k}` {'increasing' if v > 0 else 'decreasing'}"
            for k, v in cfg["monotone_constraints"].items()
        )
        return "\n".join(
            [
                "## Model details",
                "",
                f"- Champion: **{self.m['champion_label']}** with "
                f"{cfg['calibration']['method']} calibration. Challenger: {challengers}.",
                f"- Monotonic constraints on LightGBM: {monotone} ({constraints}).",
                "- Output per account: calibrated probability of default next month, a risk decile "
                f"referenced to the holdout population, and up to {cfg['n_reasons']} reason codes. "
                "The queue is ordered by the raw model score.",
                f"- Seed {cfg['seed']}; the full configuration is stored in the run's "
                "`metrics.json`.",
            ]
        )

    @staticmethod
    def intended_use() -> str:
        return (
            "## Intended use\n\n"
            "- Ordering a capacity-limited work queue (collections or proactive outreach) so "
            "analysts contact the accounts most likely to default first, with a stated reason "
            "for each.\n"
            "- Choosing queue capacity by comparing expected value at different staffing levels.\n"
            "- Methodology demonstration on public data.\n\n"
            "Out of scope: credit approval or limit decisions, pricing, any automated action "
            "against a customer without human review, and populations unlike the training data."
        )

    def data(self) -> str:
        d, s = self.m["data"], self.m["split"]
        rows = [
            ("Dataset", d["label"]),
            ("Rows", f"{d['rows']:,}"),
            ("Default rate", pct(d["default_rate"])),
            (
                "Split (train / calibration / test)",
                f"{s['train']:,} / {s['calibration']:,} / {s['test']:,}, stratified",
            ),
        ]
        features = table(
            ["Feature", "Meaning"], ((f"`{k}`", v) for k, v in FEATURE_DESCRIPTIONS.items())
        )
        protected = ", ".join(f"`{a}`" for a in PROTECTED_ATTRIBUTES)
        return (
            f"## Data\n\n{table(['Item', 'Value'], rows)}\n\n"
            "The source is a single six-month snapshot, so the split is stratified rather than "
            "out-of-time.\n\n"
            "### Features and exclusions\n\n"
            f"{len(FEATURE_DESCRIPTIONS)} engineered features, each a row-wise function of the "
            "account's own six-month history (no target encoding, no dataset-level statistics):\n\n"
            f"{features}\n\n"
            f"Protected or sensitive attributes ({protected}) are excluded from the features and "
            "used only for the fairness audit. Excluding them does not rule out proxy effects "
            "through correlated features such as the credit limit."
        )

    def performance(self) -> str:
        models = self.m["models"]

        def row(label: str, key: str, fmt: Any = num) -> tuple[str, ...]:
            return (label, *(fmt(models[n][key]) for n in self.names))

        rows = [
            row("ROC-AUC", "roc_auc"),
            row("PR-AUC", "pr_auc"),
            row("KS", "ks"),
            row("Top-decile lift", "top_decile_lift", lambda x: num(x, 2)),
            row("Brier score (calibrated)", "brier"),
            row("ECE (calibrated)", "ece"),
            row("ECE (uncalibrated)", "ece_uncalibrated"),
        ]
        for k in self.cfg["ranking"]["top_k_percents"]:
            key = str(k)
            rows.append(
                (
                    f"Precision @ top {k:g}%",
                    *(pct(models[n]["precision_at_top_pct"][key]) for n in self.names),
                )
            )
        lift = [
            (
                r["bucket"],
                r["accounts"],
                int(r["events"]),
                pct(r["event_rate"]),
                num(r["lift"], 2),
                pct(r["capture_rate"]),
            )
            for r in self.m["lift_table"]
        ]
        headers = ["Decile", "Accounts", "Defaults", "Default rate", "Lift", "Cum. capture"]
        return (
            f"## Performance on the holdout set\n\n{table(['Metric', *self.names], rows)}\n\n"
            f"{self.img('lift_curve.png', 'Cumulative capture curve')}\n\n"
            f"### Lift by decile ({self.m['champion_label']})\n\n{table(headers, lift)}"
        )

    def economics(self) -> str:
        econ, champ = self.cfg["economics"], self.champ
        cap_pct = self.cfg["ranking"]["eval_capacity_percent"]
        rows = [
            (
                f"Expected value at {cap_pct:g}% capacity ({champ['eval_capacity']:,} accounts)",
                f"{champ['ev_at_eval_capacity']:,.0f}",
            ),
            (
                "Value-maximizing capacity",
                f"{champ['ev_optimal_capacity']:,} accounts "
                f"({champ['ev_optimal_capacity_pct']:.1f}% of holdout)",
            ),
            ("Expected value at that capacity", f"{champ['ev_optimal_value']:,.0f}"),
            ("Expected value if every account is worked", f"{champ['ev_work_everyone']:,.0f}"),
        ]
        return (
            "## Queue economics (illustrative)\n\n"
            f"Assumptions from config, not real figures: cost per contact "
            f"{econ['cost_per_contact']:,.0f}, loss given default "
            f"{econ['loss_given_default']:,.0f}, share of defaulters a contact prevents "
            f"{econ['cure_rate_if_worked']:.0%}. Working an account pays off above a default "
            f"probability of {self.m['break_even_probability']:.3f}.\n\n"
            f"{table(['Quantity', 'Value'], rows)}\n\n"
            f"{self.img('expected_value.png', 'Expected value by capacity')}"
        )

    def calibration(self) -> str:
        return (
            "## Calibration\n\n"
            f"The {self.cfg['calibration']['method']} calibrator is fitted on a separate "
            f"calibration split. Holdout ECE is {num(self.champ['ece'])} after calibration and "
            f"{num(self.champ['ece_uncalibrated'])} before.\n\n"
            f"{self.img('reliability_curve.png', 'Reliability curve')}"
        )

    def explainability(self) -> str:
        top = list(self.m["global_importance"].items())[:8]
        reasons = ((r.code, r.text, ", ".join(f"`{f}`" for f in r.features)) for r in REASONS)
        return (
            "## Explainability\n\n"
            "SHAP values in log-odds space: exact TreeSHAP for LightGBM, exact linear SHAP for "
            "logistic regression. Top global drivers by mean absolute SHAP:\n\n"
            f"{table(['Feature', 'Mean abs SHAP'], ((f'`{k}`', num(v)) for k, v in top))}\n\n"
            "Reason codes group related features and report only groups that raise the "
            "account's risk:\n\n"
            f"{table(['Code', 'Reason', 'Features'], reasons)}\n\n"
            f"{self.img('shap_summary.png', 'SHAP summary')}"
        )

    def fairness(self) -> str:
        cap_pct = self.cfg["ranking"]["eval_capacity_percent"]
        summary = [
            (
                s["attribute"],
                num(s["priority_rate_ratio"], 2),
                num(s["tpr_gap"]),
                num(s["fpr_gap"]),
                num(s["max_abs_calibration_gap"]),
            )
            for s in self.m["fairness_summary"]
        ]
        slices = [
            (
                s["attribute"],
                s["group"],
                f"{s['accounts']:,}",
                pct(s["default_rate"]),
                pct(s["priority_rate"]),
                pct(s["tpr_at_capacity"]),
                f"{s['calibration_gap']:+.3f}",
                num(s["auc"]),
                "yes" if s["small_slice"] else "",
            )
            for s in self.m["fairness_slices"]
        ]
        summary_headers = [
            "Attribute",
            "Priority-rate ratio",
            "TPR gap",
            "FPR gap",
            "Max abs calibration gap",
        ]
        slice_headers = [
            "Attribute",
            "Group",
            "Accounts",
            "Default rate",
            "Priority rate",
            "TPR @ capacity",
            "Calibration gap",
            "AUC",
            "Small slice",
        ]
        return (
            "## Fairness audit\n\n"
            f"Priority means the account falls inside the top {cap_pct:g}% of the holdout queue. "
            "Priority-rate ratio is the lowest group priority rate divided by the highest; TPR "
            "gap is the spread in the share of each group's defaulters that get prioritized. "
            "Slices under 100 accounts are flagged and left out of the summary. Being worked can "
            "be a burden (collections contact) or a benefit (early hardship help), so both "
            "selection parity and error-rate parity are reported.\n\n"
            f"{table(summary_headers, summary)}\n\n{table(slice_headers, slices)}\n\n"
            "Differences in priority rate mostly follow differences in observed default rate. "
            "TPR, FPR and calibration gaps are the signals that equally risky accounts are "
            f"treated differently.{self._largest_tpr_gap()}"
        )

    def _largest_tpr_gap(self) -> str:
        reliable = [
            s
            for s in self.m["fairness_slices"]
            if not s["small_slice"] and s["tpr_at_capacity"] is not None
        ]
        if not self.m["fairness_summary"] or not reliable:
            return ""
        worst = max(self.m["fairness_summary"], key=lambda s: s["tpr_gap"])["attribute"]
        groups = [s for s in reliable if s["attribute"] == worst]
        hi = max(groups, key=lambda s: s["tpr_at_capacity"])
        lo = min(groups, key=lambda s: s["tpr_at_capacity"])
        return (
            f" On this run the largest TPR gap is on `{worst}`: {pct(hi['tpr_at_capacity'])} of "
            f"defaulters in `{hi['group']}` are prioritized versus "
            f"{pct(lo['tpr_at_capacity'])} for `{lo['group']}`."
        )

    def stability(self) -> str:
        return (
            "## Stability\n\n"
            f"PSI of champion scores, training vs holdout: {num(self.m['psi_train_vs_test'])} "
            "(under 0.1 is conventionally stable). In production the same check runs between "
            "the development sample and each new scoring month."
        )

    @staticmethod
    def limitations() -> str:
        return (
            "## Limitations\n\n"
            "- One 2005 Taiwanese snapshot: no time axis, so no out-of-time validation, "
            "seasonality or drift.\n"
            "- The outcome is next-month default, not loss amount or recoverability. The queue "
            "ranks who is likely to default, not who responds to contact (uplift).\n"
            "- The economic parameters are illustrative placeholders and drive the capacity "
            "recommendation.\n"
            "- Undocumented education and marriage codes are pooled as other/unknown.\n"
            "- Reason codes describe the model, not causes. They are adverse-action style, not "
            "legal notices."
        )

    def render(self) -> str:
        sections = [
            self.header(),
            self.details(),
            self.intended_use(),
            self.data(),
            self.performance(),
            self.economics(),
            self.calibration(),
            self.explainability(),
            self.fairness(),
            self.stability(),
            self.limitations(),
        ]
        return "\n\n".join(sections).replace("\n\n\n", "\n\n") + "\n"


def render_model_card(metrics: dict[str, Any], img_dir: str | None = None) -> str:
    """Markdown model card; ``img_dir`` is the chart directory relative to the card, if any."""
    return _Card(metrics, img_dir).render()
